version: '3.8'
services:
  websocket-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "0:8000"
    depends_on:
      - redis
    environment:
      - SERVER_ID=ws{{.Task.Slot}}
      - REDIS_HOST=redis:6379

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - websocket-server

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

networks:
  default:
    driver: bridge

volumes:
  redis_data: