version: '3.8'
services:
  websocket-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - websocket-server

networks:
  default:
    driver: bridge